---
- name: ansible practice
  hosts: all
  tasks:
    - name: check uptime
      shell: uptime
    - name: check date
      shell: date
    - name: copy the file 
      copy:
        src: /tmp/vani.txt
        dest: /tmp/vaninew.txt
